query getOptions($input: [ProcInput]) {
	ContextProc(input: $input) {
		uuid
		name
		cacheExpires
		error
		results {
			key
			label
			default
			value
			type
			parent
			target
			properties
			order
		}
	}
}
