query getContext($input: [ProcInput]) {
	ContextProc(input: $input) {
		cacheExpires
		name
		uuid
		results {
			default
			key
			label
			order
			parent
			properties
			target
			type
			value
		}
	}
}
